version: "3"
services:
  mysql:
    container_name: tott-mysql
    image: mysql/mysql-server:8.0
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: Asia/Seoul
    volumes:
      - mysql-data:/var/lib/mysql
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    ports:
      - '3306:3306'

  redis:
    container_name: tott-redis
    image: "redis:latest"
    ports:
      - "6379:6379"

  database-adminer:
    container_name: tott-db-adminer
    image: adminer:latest
    ports:
      - "18080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=db-mysql
      - ADMINER_DESIGN=hydra
      - ADMINER_PLUGINS=tables-filter tinymce

volumes:
  mysql-data:
  mongo-data: